### PR TITLE
Simplify  the matchLabels selector

### PR DESCRIPTION
**Pull request by adamkingit**

### CODE REVIEW

**Comment by alewitt2** [comment]
If you do this, anyone that applied the old version will be broken. Matchlabels is immutable, so you'd have to delete the running razeedash and apply the new one or force apply the new one

**Comment by adamkingit** [comment]
It has issues the old way too. I knew you had experienced this pain before and figured you could help me thread the needle.

**Comment by alewitt2** [comment]
Not sure there is any way to thread without breaking someone. What's broken about how it currently is?

**Comment by alewitt2** [comment]
I guess anyone before this update made it in is broken, and after this update made it in, will be broken once we switch back

**Pull request merged**
